name: CI

on:
  push

jobs:
  build:
    name: Ci
    environment: dev
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install
        run: echo ${{ toJson(github) }}

      # - name: Build tests
      #   run: npm run build
