name: CI

on:
  push

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      APP_NAME: Adam
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install
        run: npm ci

      - name: Build tests
        run: npm run build

      - name: Run server in container
        run:  |
          docker-compose build --build-arg APP=${APP_NAME}
          docker-compose up -d
      - name: Run tests
        run: npm run tests
