name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install
        run: npm ci

      - name: Build tests
        run: npm run build
  
  test-trigger:
    name: test
    environment: staging
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install
        run: npm ci

