name: Test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    name: CI build
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install
        run: npm ci
